apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtube-application
  labels:
    app: youtube
spec:
  replicas: 3
  selector:
    matchLabels:
      app: youtube
  template:
    metadata:
      labels:
        app: youtube
    spec:
      containers:
      - name: youtube-app
        image: manojsiriparthi/youtube:app1
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
